# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d3711d061296a4c8c5ffe52235a1d784dd9ff51817ad2a75b9ccdc55ad9390d77bb5f90a159dfd2b52078eb563e98465a621ae47698ca6cb558aa83a0395825

test:
  secret_key_base: f254973e453d47fe3997e2e95b912976adfbd2c4803218787898bc96cd3f1b54b38c5ae959be851b264537aa760dffeba8f3028ee5e9b18fe186d28e2a138bf1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
